import type BaseDialog from "./base-dialog";

// ---------------- 声明全局组件标签类型提示 ----------------
// declare module "@vue/runtime-core"
declare module "vue" {
  type Router = typeof import("vue-router");
  type Element = typeof import("element-plus");

  /**
   * 自定义全局组件获得 Volar 提示
   * - 自定义的全局组件需要在这里声明下才能获得 Volar 类型提示
   */
  export interface GlobalComponents {
    BaseDialog: typeof BaseDialog

    RouterLink: Router["RouterLink"]
    RouterView: Router["RouterView"]

    // 用到哪些再手动放开注释
    // ElAffix: Element["ElAffix"]
    // ElAlert: Element["ElAlert"]
    // ElAside: Element["ElAside"]
    // ElAutocomplete: Element["ElAutocomplete"]
    // ElAvatar: Element["ElAvatar"]
    // ElAnchor: Element["ElAnchor"]
    // ElAnchorLink: Element["ElAnchorLink"]
    // ElBacktop: Element["ElBacktop"]
    // ElBadge: Element["ElBadge"]
    // ElBreadcrumb: Element["ElBreadcrumb"]
    // ElBreadcrumbItem: Element["ElBreadcrumbItem"]
    ElButton: Element["ElButton"]
    ElButtonGroup: Element["ElButtonGroup"]
    // ElCalendar: Element["ElCalendar"]
    // ElCard: Element["ElCard"]
    // ElCarousel: Element["ElCarousel"]
    // ElCarouselItem: Element["ElCarouselItem"]
    ElCascader: Element["ElCascader"]
    // ElCascaderPanel: Element["ElCascaderPanel"]
    ElCheckbox: Element["ElCheckbox"]
    ElCheckboxButton: Element["ElCheckboxButton"]
    ElCheckboxGroup: Element["ElCheckboxGroup"]
    // ElCol: Element["ElCol"]
    // ElCollapse: Element["ElCollapse"]
    // ElCollapseItem: Element["ElCollapseItem"]
    // ElCollapseTransition: Element["ElCollapseTransition"]
    ElColorPicker: Element["ElColorPicker"]
    // ElContainer: Element["ElContainer"]
    ElConfigProvider: Element["ElConfigProvider"]
    ElDatePicker: Element["ElDatePicker"]
    // ElDialog: Element["ElDialog"]
    ElDivider: Element["ElDivider"]
    // ElDrawer: Element["ElDrawer"]
    ElDropdown: Element["ElDropdown"]
    ElDropdownItem: Element["ElDropdownItem"]
    ElDropdownMenu: Element["ElDropdownMenu"]
    ElEmpty: Element["ElEmpty"]
    // ElFooter: Element["ElFooter"]
    ElForm: Element["ElForm"]
    ElFormItem: Element["ElFormItem"]
    // ElHeader: Element["ElHeader"]
    ElIcon: Element["ElIcon"]
    // ElImage: Element["ElImage"]
    // ElImageViewer: Element["ElImageViewer"]
    ElInput: Element["ElInput"]
    ElInputNumber: Element["ElInputNumber"]
    // ElLink: Element["ElLink"]
    // ElMain: Element["ElMain"]
    // ElMenu: Element["ElMenu"]
    // ElMenuItem: Element["ElMenuItem"]
    // ElMenuItemGroup: Element["ElMenuItemGroup"]
    ElOption: Element["ElOption"]
    // ElOptionGroup: Element["ElOptionGroup"]
    // ElPageHeader: Element["ElPageHeader"]
    ElPagination: Element["ElPagination"]
    ElPopconfirm: Element["ElPopconfirm"]
    // ElPopper: Element["ElPopper"]
    ElPopover: Element["ElPopover"]
    // ElProgress: Element["ElProgress"]
    ElRadio: Element["ElRadio"]
    ElRadioButton: Element["ElRadioButton"]
    ElRadioGroup: Element["ElRadioGroup"]
    // ElRate: Element["ElRate"]
    // ElRow: Element["ElRow"]
    ElScrollbar: Element["ElScrollbar"]
    ElSelect: Element["ElSelect"]
    // ElSlider: Element["ElSlider"]
    // ElStep: Element["ElStep"]
    // ElSteps: Element["ElSteps"]
    // ElSubMenu: Element["ElSubMenu"]
    ElSwitch: Element["ElSwitch"]
    // ElTabPane: Element["ElTabPane"]
    ElTable: Element["ElTable"]
    ElTableColumn: Element["ElTableColumn"]
    // ElTabs: Element["ElTabs"]
    // ElTag: Element["ElTag"]
    ElText: Element["ElText"]
    // ElTimePicker: Element["ElTimePicker"]
    // ElTimeSelect: Element["ElTimeSelect"]
    // ElTimeline: Element["ElTimeline"]
    // ElTimelineItem: Element["ElTimelineItem"]
    ElTooltip: Element["ElTooltip"]
    // ElTransfer: Element["ElTransfer"]
    // ElTree: Element["ElTree"]
    // ElTreeV2: Element["ElTreeV2"]
    ElTreeSelect: Element["ElTreeSelect"]
    // ElUpload: Element["ElUpload"]
    // ElSpace: Element["ElSpace"]
    // ElSkeleton: Element["ElSkeleton"]
    // ElSkeletonItem: Element["ElSkeletonItem"]
    // ElStatistic: Element["ElStatistic"]
    // ElCheckTag: Element["ElCheckTag"]
    // ElDescriptions: Element["ElDescriptions"]
    // ElDescriptionsItem: Element["ElDescriptionsItem"]
    // ElResult: Element["ElResult"]
    ElSelectV2: Element["ElSelectV2"]
    ElTableV2: Element["ElTableV2"]
    // ElWatermark: Element["ElWatermark"]
    // ElTour: Element["ElTour"]
    // ElTourStep: Element["ElTourStep"]
  }
}
