import type BaseDialog from "./base-dialog";

// ---------------- 声明全局组件标签类型提示 ----------------
// declare module "@vue/runtime-core"
declare module "vue" {
  type Router = typeof import("vue-router");
  type El = typeof import("element-plus");

  /**
   * 自定义全局组件获得 Volar 提示
   * - 自定义的全局组件需要在这里声明下才能获得 Volar 类型提示
   */
  export interface GlobalComponents {
    BaseDialog: typeof BaseDialog

    RouterLink: Router["RouterLink"]
    RouterView: Router["RouterView"]

    // 用到哪些再手动放开注释
    // ElAffix: El["ElAffix"]
    // ElAlert: El["ElAlert"]
    // ElAside: El["ElAside"]
    // ElAutocomplete: El["ElAutocomplete"]
    // ElAvatar: El["ElAvatar"]
    // ElAnchor: El["ElAnchor"]
    // ElAnchorLink: El["ElAnchorLink"]
    // ElBacktop: El["ElBacktop"]
    // ElBadge: El["ElBadge"]
    // ElBreadcrumb: El["ElBreadcrumb"]
    // ElBreadcrumbItem: El["ElBreadcrumbItem"]
    ElButton: El["ElButton"]
    ElButtonGroup: El["ElButtonGroup"]
    // ElCalendar: El["ElCalendar"]
    // ElCard: El["ElCard"]
    // ElCarousel: El["ElCarousel"]
    // ElCarouselItem: El["ElCarouselItem"]
    ElCascader: El["ElCascader"]
    // ElCascaderPanel: El["ElCascaderPanel"]
    ElCheckbox: El["ElCheckbox"]
    ElCheckboxButton: El["ElCheckboxButton"]
    ElCheckboxGroup: El["ElCheckboxGroup"]
    // ElCol: El["ElCol"]
    // ElCollapse: El["ElCollapse"]
    // ElCollapseItem: El["ElCollapseItem"]
    // ElCollapseTransition: El["ElCollapseTransition"]
    ElColorPicker: El["ElColorPicker"]
    // ElContainer: El["ElContainer"]
    ElConfigProvider: El["ElConfigProvider"]
    ElDatePicker: El["ElDatePicker"]
    // ElDialog: El["ElDialog"]
    ElDivider: El["ElDivider"]
    // ElDrawer: El["ElDrawer"]
    ElDropdown: El["ElDropdown"]
    ElDropdownItem: El["ElDropdownItem"]
    ElDropdownMenu: El["ElDropdownMenu"]
    ElEmpty: El["ElEmpty"]
    // ElFooter: El["ElFooter"]
    ElForm: El["ElForm"]
    ElFormItem: El["ElFormItem"]
    // ElHeader: El["ElHeader"]
    ElIcon: El["ElIcon"]
    // ElImage: El["ElImage"]
    // ElImageViewer: El["ElImageViewer"]
    ElInput: El["ElInput"]
    ElInputNumber: El["ElInputNumber"]
    // ElLink: El["ElLink"]
    // ElMain: El["ElMain"]
    // ElMenu: El["ElMenu"]
    // ElMenuItem: El["ElMenuItem"]
    // ElMenuItemGroup: El["ElMenuItemGroup"]
    ElOption: El["ElOption"]
    // ElOptionGroup: El["ElOptionGroup"]
    // ElPageHeader: El["ElPageHeader"]
    ElPagination: El["ElPagination"]
    ElPopconfirm: El["ElPopconfirm"]
    // ElPopper: El["ElPopper"]
    ElPopover: El["ElPopover"]
    // ElProgress: El["ElProgress"]
    ElRadio: El["ElRadio"]
    ElRadioButton: El["ElRadioButton"]
    ElRadioGroup: El["ElRadioGroup"]
    // ElRate: El["ElRate"]
    // ElRow: El["ElRow"]
    ElScrollbar: El["ElScrollbar"]
    ElSelect: El["ElSelect"]
    // ElSlider: El["ElSlider"]
    // ElStep: El["ElStep"]
    // ElSteps: El["ElSteps"]
    // ElSubMenu: El["ElSubMenu"]
    ElSwitch: El["ElSwitch"]
    // ElTabPane: El["ElTabPane"]
    ElTable: El["ElTable"]
    ElTableColumn: El["ElTableColumn"]
    // ElTabs: El["ElTabs"]
    // ElTag: El["ElTag"]
    ElText: El["ElText"]
    // ElTimePicker: El["ElTimePicker"]
    // ElTimeSelect: El["ElTimeSelect"]
    // ElTimeline: El["ElTimeline"]
    // ElTimelineItem: El["ElTimelineItem"]
    ElTooltip: El["ElTooltip"]
    // ElTransfer: El["ElTransfer"]
    // ElTree: El["ElTree"]
    // ElTreeV2: El["ElTreeV2"]
    ElTreeSelect: El["ElTreeSelect"]
    // ElUpload: El["ElUpload"]
    // ElSpace: El["ElSpace"]
    // ElSkeleton: El["ElSkeleton"]
    // ElSkeletonItem: El["ElSkeletonItem"]
    // ElStatistic: El["ElStatistic"]
    // ElCheckTag: El["ElCheckTag"]
    // ElDescriptions: El["ElDescriptions"]
    // ElDescriptionsItem: El["ElDescriptionsItem"]
    // ElResult: El["ElResult"]
    ElSelectV2: El["ElSelectV2"]
    ElTableV2: El["ElTableV2"]
    // ElWatermark: El["ElWatermark"]
    // ElTour: El["ElTour"]
    // ElTourStep: El["ElTourStep"]
  }
}
